version: '3.7'

services:
  mysql:
    image: mysql:8.0
    hostname: mysql
    container_name: mysql
    ports:
      - '3306:3306'
    volumes:
      - ./mysql-data:/var/lib/mysql
      - ./mysql-config:/etc/mysql/conf.d
    command: --default-authentication-plugin=mysql_native_password --port=3306
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: greenrun
      USER: 1000
    networks:
      greenrun_network:
        ipv4_address: 172.21.0.3

  app:
    build: .
    container_name: greenrun
    hostname: greenrun
    links:
      - mysql
    ports:
      - '3000:3000'
    volumes:
      - ./:/usr/app
      - ./node_modules:/usr/app/node_modules
    tty: true
    networks:
      greenrun_network:
        ipv4_address: 172.21.0.5

  adminer:
    image: adminer
    container_name: adminer
    ports:
      - 8081:8081
    networks:
      greenrun_network:
        ipv4_address: 172.21.0.4

  redis:
    image: redis
    hostname: redis
    container_name: redis
    ports:
      - 6379:6379
    volumes:
      - ./redis/data:/data
      - ./redis/redis.conf:/usr/local/etc/redis/redis.conf
    command:
      - redis-server
      - /usr/local/etc/redis/redis.conf
    networks:
      greenrun_network:
        ipv4_address: 172.21.0.2

networks:
    greenrun_network:
      ipam:
        driver: default
        config:
          - subnet: 172.21.0.1/16